name: Run Tests

on: [push, pull_request]

jobs:
  setup-services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: tienda3_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: 🛠️ Checkout código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.7  

      - name: 📦 Instalar dependencias
        run: |
          gem install bundler --no-document
          bundle config set deployment 'true'
          bundle install --jobs 4 --retry 3

      - name: 🗄️ Configurar base de datos
        run: bin/rails db:drop db:create db:migrate

  test-unit:
    runs-on: ubuntu-latest
    needs: setup-services
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/tienda3_test"
      REDIS_URL: "redis://localhost:6379/0"

    steps:
      - name: 🛠️ Checkout código
        uses: actions/checkout@v4

      - name: ✅ Ejecutar pruebas unitarias
        run: |
          mkdir -p tmp
          bundle exec rails test | tee tmp/test-results-unit.log      

      - name: 📤 Guardar resultados de pruebas unitarias
        uses: actions/upload-artifact@v4
        with:
          name: test-results-unit
          path: tmp/test-results-unit.log
          retention-days: 7

  test-system:
    runs-on: ubuntu-latest
    needs: setup-services
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/tienda3_test"
      REDIS_URL: "redis://localhost:6379/0"

    steps:
      - name: 🛠️ Checkout código
        uses: actions/checkout@v4

      - name: Install Chrome and WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: ✅ Ejecutar pruebas de sistema individualmente
        run: |
          mkdir -p tmp
          for test_file in $(find test/system -name "*.rb"); do
            echo "Ejecutando: $test_file"
            bundle exec rails test $test_file | tee -a tmp/test-results-system.log
          done
        
      - name: 📤 Guardar resultados de pruebas de sistema
        uses: actions/upload-artifact@v4
        with:
          name: test-results-system
          path: tmp/test-results-system.log
          retention-days: 7
