name: Run Tests

on: [push, pull_request]  # Ejecuta en cada push y PR

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tienda3_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/tienda3_test"

    steps:
      - name: 🛠️ Checkout código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.7  # Ajusta según tu versión

      - name: 📦 Instalar dependencias
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      
      - name: Install Chrome and WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: 🗄️ Configurar base de datos
        run: |
          bin/rails db:drop db:create db:migrate
        

      - name: ✅ Ejecutar pruebas (incluyendo System Tests)
        run: bundle exec rails test test/system/test_registro_usuario.rb
        
