name: Run Tests

on: [push, pull_request]  # Ejecuta en cada push y PR

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tienda3_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/tienda3_test"

    steps:
      - name: 🛠️ Checkout código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.7  # Ajusta según tu versión

      - name: 📦 Instalar dependencias
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: 🖥️ Instalar Chromium y ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROME_VERSION=$(chromium-browser --version | awk '{print $2}')
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
          chromium-browser --version

      - name: 🗄️ Configurar base de datos
        run: |
          bin/rails db:drop db:create db:migrate

      - name: 🔄 Iniciar servidor de pantalla virtual (Xvfb)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1280x1024x24 &

      - name: ✅ Ejecutar pruebas (incluyendo System Tests)
        env:
          DISPLAY: ":99"
        run: bundle exec rails test test/system/test_registro_usuario.rb
